//! Milestone 665 US2 T020 — `--help` discoverability regression test.
//!
//! Anchors the SC-004 discoverability guarantee: operators running
//! `waybill sbom scan --help` see the `--no-binary-scan` flag, its
//! accepted value `go`, and enough context to know why they'd flip
//! it (either the trade-off "Go-binary module attribution" or the
//! perf benefit "mongo" wall-time reference).
//!
//! Guards against three specific regressions:
//! 1. Flag renamed / removed → the `--no-binary-scan` grep fails.
//! 2. Enum variant renamed → the `go` value grep fails.
//! 3. Description reduced to something operators can't act on →
//!    neither the trade-off nor the perf-benefit keyword shows up.

use std::process::Command;

fn scan_help_stdout() -> String {
    let bin = env!("CARGO_BIN_EXE_waybill");
    let output = Command::new(bin)
        .args(["sbom", "scan", "--help"])
        .output()
        .expect("waybill should run");
    assert!(
        output.status.success(),
        "`waybill sbom scan --help` failed: stderr={}",
        String::from_utf8_lossy(&output.stderr),
    );
    String::from_utf8(output.stdout).expect("--help stdout must be UTF-8")
}

/// SC-004 anchor: `--help` must name the flag, its accepted value,
/// and one of the perf-benefit / trade-off keywords. Any one of
/// these failing means an operator wouldn't be able to find the
/// flag OR wouldn't know when to use it.
#[test]
fn help_lists_no_binary_scan_flag_with_accepted_value_and_context() {
    let help = scan_help_stdout();

    // (1) Flag name present.
    assert!(
        help.contains("--no-binary-scan"),
        "expected `--no-binary-scan` in `waybill sbom scan --help` \
         output — flag was renamed or removed. Full stdout:\n{help}",
    );

    // (2) Accepted value `go` present — the possible-values list is
    // auto-generated by clap's `value_enum` derive from
    // BinaryScanMode::Go's `#[clap(name = "go")]`.
    assert!(
        help.contains("go"),
        "expected accepted value `go` in `waybill sbom scan --help` \
         output — BinaryScanMode::Go's clap name was renamed. Full stdout:\n{help}",
    );

    // (3) Context — at least one of the trade-off or perf-benefit
    // keywords. Multiple candidates so this passes even if the
    // long_help text is reworded for style — as long as the intent
    // is preserved. If NONE match, the description has drifted to
    // something operators can't act on and SC-004 fails.
    let context_keywords = [
        "Go-binary",  // T018 trade-off phrasing
        "BuildInfo",  // v1-mode explanation body
        "mongo",      // T018 + T019 perf benefit reference
        "WHEN TO USE", // T019 quickstart-derived guidance
    ];
    let hit = context_keywords
        .iter()
        .find(|k| help.contains(*k));
    assert!(
        hit.is_some(),
        "expected `waybill sbom scan --help` output to contain at \
         least one of {context_keywords:?} — none matched. The \
         description was reduced to something operators can't act \
         on. Restore the trade-off / perf-benefit context per T018+T019. \
         Full stdout:\n{help}",
    );
}
