//! Milestone 177: graph-completeness reachability signal integration tests.
//!
//! Covers:
//!
//! * **US1 (P1)**: downstream reachability tool can machine-check the
//!   `transitive-edges-unresolvable` substring in
//!   `mikebom:graph-completeness-reason` and gate its analysis.
//! * **US2 (P1)**: constraint-only scans flip
//!   `mikebom:graph-completeness` from `"complete"` (pre-177 misleading)
//!   to `"partial"` and gain the new reason code.
//! * **US3 (P2)**: polyglot scans enumerate ONLY affected ecosystems in
//!   the reason detail; safe ecosystems (lockfile-resolved) are NOT
//!   named. Multi-ecosystem case is alphabetically sorted.
//! * **SC-002**: fully-resolved scans stay `"complete"`; new code
//!   absent.
//! * **SC-004 composition**: new code composes with existing codes via
//!   the `join_reason_codes` semicolon convention.
//!
//! Mirrors the m175 (`design_tier_advisory.rs`) and m176
//! (`workspace_visibility.rs`) integration-test scaffolding:
//! `assert_cmd`-based release-independent subprocess with
//! `apply_fake_home_env` for HOME isolation.

use std::path::Path;
use std::process::Command;

mod common;
use common::bin;

/// Load-bearing stable substring per FR-003 + contracts/reason-code-wire-format.md.
/// Reachability tools `grep -F` this token to detect unreliable graphs.
const CODE_SUBSTRING: &str = "transitive-edges-unresolvable: ";

/// Scan `path` with `--offline`, return (parsed CDX SBOM, captured stderr).
fn scan_cdx(path: &Path) -> (serde_json::Value, String) {
    let tmp = tempfile::NamedTempFile::new().expect("tempfile");
    let out_path = tmp.path().to_path_buf();
    let fake_home = tempfile::tempdir().expect("fake-home tempdir");

    let mut cmd = Command::new(bin());
    common::normalize::apply_fake_home_env(&mut cmd, fake_home.path());
    cmd.arg("--offline")
        .arg("sbom")
        .arg("scan")
        .arg("--path")
        .arg(path)
        .arg("--output")
        .arg(&out_path)
        .arg("--no-deep-hash");

    let output = cmd.output().expect("mikebom should run");
    assert!(
        output.status.success(),
        "scan failed (exit={:?}): stderr={}",
        output.status.code(),
        String::from_utf8_lossy(&output.stderr)
    );
    let raw = std::fs::read_to_string(&out_path).expect("read sbom");
    let sbom = serde_json::from_str(&raw).expect("valid JSON");
    let stderr = String::from_utf8_lossy(&output.stderr).into_owned();
    (sbom, stderr)
}

/// Extract the doc-scope `mikebom:graph-completeness` value.
/// Returns `None` when the annotation is absent (e.g., empty scan).
fn graph_completeness(sbom: &serde_json::Value) -> Option<String> {
    sbom["metadata"]["properties"]
        .as_array()?
        .iter()
        .find(|p| p["name"] == "mikebom:graph-completeness")?["value"]
        .as_str()
        .map(String::from)
}

/// Extract the doc-scope `mikebom:graph-completeness-reason` value.
/// Returns `None` when the annotation is absent (Complete scans).
fn graph_completeness_reason(sbom: &serde_json::Value) -> Option<String> {
    sbom["metadata"]["properties"]
        .as_array()?
        .iter()
        .find(|p| p["name"] == "mikebom:graph-completeness-reason")?["value"]
        .as_str()
        .map(String::from)
}

// Fixture helpers.

fn write_pip_requirements_only(dir: &Path) {
    std::fs::write(
        dir.join("requirements.txt"),
        "requests>=2.31.0\n\
         click>=8.1.7\n\
         pyyaml>=6.0\n",
    )
    .expect("write requirements.txt");
}

fn write_cargo_with_lockfile(dir: &Path) {
    std::fs::create_dir_all(dir.join("src")).expect("mkdir src");
    std::fs::write(
        dir.join("Cargo.toml"),
        "[package]\n\
         name = \"safe-crate\"\n\
         version = \"0.1.0\"\n\
         edition = \"2021\"\n\
         \n\
         [dependencies]\n\
         serde = \"1.0\"\n",
    )
    .expect("write Cargo.toml");
    std::fs::write(dir.join("src/lib.rs"), "").expect("write lib.rs");
    std::fs::write(
        dir.join("Cargo.lock"),
        "# This file is automatically @generated by Cargo.\n\
         # It is not intended for manual editing.\n\
         version = 4\n\
         \n\
         [[package]]\n\
         name = \"safe-crate\"\n\
         version = \"0.1.0\"\n\
         dependencies = [\n\
          \"serde\",\n\
         ]\n\
         \n\
         [[package]]\n\
         name = \"serde\"\n\
         version = \"1.0.219\"\n\
         source = \"registry+https://github.com/rust-lang/crates.io-index\"\n\
         checksum = \"25b0e9c19a03cb0c9c67b0aabff45ab61ce9e21afc0ea34d2aaddadaa77dda1a\"\n",
    )
    .expect("write Cargo.lock");
}

fn write_composer_manifest_only(dir: &Path) {
    std::fs::write(
        dir.join("composer.json"),
        "{\
           \"name\": \"m177/composer-design-tier\", \
           \"require\": {\
             \"symfony/console\": \"^6.4\"\
           }\
         }",
    )
    .expect("write composer.json");
}

// -----------------------------------------------------------------------
// US1 (P1) — reachability tool machine-check
// -----------------------------------------------------------------------

/// SC-001 + SC-005 — a reachability tool's jq-substring check returns
/// `true` on a constraint-only pip scan. The exact substring
/// `"transitive-edges-unresolvable: "` (with trailing colon-space) is
/// the load-bearing wire signal.
#[test]
fn t001_us1_machine_check_true_on_design_tier_scan() {
    let tmp = tempfile::tempdir().expect("tempdir");
    write_pip_requirements_only(tmp.path());

    let (sbom, _stderr) = scan_cdx(tmp.path());

    let reason = graph_completeness_reason(&sbom).expect(
        "US1: mikebom:graph-completeness-reason MUST be present when the classifier fires",
    );
    assert!(
        reason.contains(CODE_SUBSTRING),
        "US1 SC-001: reason value MUST contain {CODE_SUBSTRING:?} substring; got {reason:?}"
    );
    assert!(
        reason.contains("transitive-edges-unresolvable: pypi"),
        "US1 SC-001: reason value MUST name the affected ecosystem (pypi); got {reason:?}"
    );
}

/// US2 acceptance scenario 1 — `graph-completeness` value flips from
/// pre-177 `"complete"` to post-177 `"partial"` on the same fixture.
/// This is the behavior-change assertion (mikebom-side deliverable).
#[test]
fn t002_us1_partial_graph_completeness_value() {
    let tmp = tempfile::tempdir().expect("tempdir");
    write_pip_requirements_only(tmp.path());

    let (sbom, _stderr) = scan_cdx(tmp.path());

    let value = graph_completeness(&sbom)
        .expect("US1: mikebom:graph-completeness MUST be present on non-empty scan");
    assert_eq!(
        value, "partial",
        "US1: graph-completeness MUST be `partial` (not `complete`) on constraint-only scan; got {value:?}"
    );
}

// -----------------------------------------------------------------------
// US2 (P1) — offline orthogonality + empty-scan edge case
// -----------------------------------------------------------------------

/// FR-005 + SC-005 offline-orthogonality gate — the reason code MUST
/// fire under `--offline`. `scan_cdx` already passes `--offline`; this
/// test makes the FR-005 contract explicit and locks it in.
#[test]
fn t003_us2_reason_fires_under_offline() {
    let tmp = tempfile::tempdir().expect("tempdir");
    write_pip_requirements_only(tmp.path());

    // scan_cdx invokes with `--offline` unconditionally per helper design.
    let (sbom, _stderr) = scan_cdx(tmp.path());

    let reason = graph_completeness_reason(&sbom).expect(
        "FR-005: reason MUST fire under --offline (network state is orthogonal)",
    );
    assert!(
        reason.contains(CODE_SUBSTRING),
        "FR-005: --offline scan MUST still emit the m177 code; got {reason:?}"
    );
}

/// Edge case — empty scan target (zero manifests, zero components) →
/// the graph-completeness annotation itself isn't emitted; the reason
/// cannot appear standalone. Verifies the classifier doesn't crash or
/// mis-fire on the empty case.
#[test]
fn t004_us2_empty_scan_target_silent() {
    let tmp = tempfile::tempdir().expect("tempdir");
    std::fs::write(tmp.path().join("README.txt"), b"empty scan target\n")
        .expect("write README");

    let (sbom, _stderr) = scan_cdx(tmp.path());

    // On empty scans, either the annotation is absent OR (if it exists)
    // its value must NOT contain the m177 code (per Edge Cases in spec).
    match graph_completeness_reason(&sbom) {
        None => { /* annotation absent — acceptable */ }
        Some(reason) => {
            assert!(
                !reason.contains(CODE_SUBSTRING),
                "empty scan MUST NOT emit m177 code; got reason value {reason:?}"
            );
        }
    }
}

// -----------------------------------------------------------------------
// US3 (P2) — polyglot ecosystem enumeration + safe-fixture negative + composition
// -----------------------------------------------------------------------

/// US3 SC-003 — polyglot scan (cargo lockfile-resolved + pip
/// constraint-only) names ONLY pypi in the reason detail, NOT cargo.
/// Reachability tools can safely analyze the cargo subgraph while
/// filtering out pypi.
#[test]
fn t005_us3_polyglot_pypi_only_not_cargo() {
    let tmp = tempfile::tempdir().expect("tempdir");
    write_cargo_with_lockfile(&tmp.path().join("rust"));
    std::fs::write(
        tmp.path().join("requirements.txt"),
        "requests>=2.31.0\n",
    )
    .expect("write requirements.txt");

    let (sbom, _stderr) = scan_cdx(tmp.path());

    let reason = graph_completeness_reason(&sbom)
        .expect("US3: reason MUST be present on polyglot mixed-tier scan");
    assert!(
        reason.contains("transitive-edges-unresolvable: pypi"),
        "US3 SC-003: reason MUST name pypi (constraint-only ecosystem); got {reason:?}"
    );
    // Cargo is source-tier (lockfile-resolved), so MUST NOT appear in
    // the m177 code's detail.
    assert!(
        !reason.contains("transitive-edges-unresolvable: cargo"),
        "US3 SC-003: reason MUST NOT name cargo (source-tier-resolved); got {reason:?}"
    );
    assert!(
        !reason.contains("transitive-edges-unresolvable: cargo, pypi"),
        "US3 SC-003: reason MUST NOT include cargo in the m177 code's ecosystem list; got {reason:?}"
    );
}

/// US3 SC-003 multi-ecosystem — pypi + composer both constraint-only
/// → reason names both, alphabetically sorted.
#[test]
fn t006_us3_multi_ecosystem_sorted_dedup() {
    let tmp = tempfile::tempdir().expect("tempdir");
    write_pip_requirements_only(tmp.path());
    write_composer_manifest_only(tmp.path());

    let (sbom, _stderr) = scan_cdx(tmp.path());

    let reason = graph_completeness_reason(&sbom)
        .expect("US3: reason MUST be present on multi-ecosystem constraint-only scan");
    assert!(
        reason.contains("transitive-edges-unresolvable: composer, pypi"),
        "US3 SC-003 sort: reason MUST list ecosystems alphabetically as `composer, pypi`; got {reason:?}"
    );
}

/// SC-002 — fully-resolved scan (cargo with Cargo.lock ONLY, no pip)
/// stays `"complete"`. m177 code MUST NOT appear.
#[test]
fn t007_sc002_safe_fixture_stays_complete() {
    let tmp = tempfile::tempdir().expect("tempdir");
    write_cargo_with_lockfile(tmp.path());

    let (sbom, _stderr) = scan_cdx(tmp.path());

    let value = graph_completeness(&sbom)
        .expect("SC-002: mikebom:graph-completeness MUST be present on non-empty scan");
    assert_eq!(
        value, "complete",
        "SC-002: fully-resolved (cargo lockfile-only) scan MUST stay `complete`; got {value:?}"
    );
    // Reason annotation is typically absent when complete, but if
    // present it MUST NOT contain the m177 code.
    if let Some(reason) = graph_completeness_reason(&sbom) {
        assert!(
            !reason.contains(CODE_SUBSTRING),
            "SC-002: reason value MUST NOT contain m177 code on safe scan; got {reason:?}"
        );
    }
}

/// SC-004 composition — a scan that triggers BOTH the m177 code AND
/// another existing code produces a semicolon-joined reason value.
/// Multi-workspace pip fixture is expected to fire
/// `MultiEcosystemPartialRoot` (from m127 root-selector's
/// multi-workspace behavior) alongside m177's
/// `TransitiveEdgesUnresolvable`. If the fixture doesn't naturally
/// trigger both codes, the test soft-skips per U1 fallback documented
/// in tasks.md — the wire-format contract is fully asserted by the
/// unit test `transitive_edges_unresolvable_composes_with_orphaned`
/// in `reason_codes.rs`.
#[test]
fn t008_sc004_composition_with_existing_code() {
    let tmp = tempfile::tempdir().expect("tempdir");
    // Two disjoint pip workspaces at subdir roots.
    std::fs::create_dir_all(tmp.path().join("workspace_a")).expect("mkdir a");
    std::fs::create_dir_all(tmp.path().join("workspace_b")).expect("mkdir b");
    std::fs::write(
        tmp.path().join("workspace_a/requirements.txt"),
        "requests>=2.31.0\n",
    )
    .expect("write a/requirements.txt");
    std::fs::write(
        tmp.path().join("workspace_b/requirements.txt"),
        "click>=8.1.7\n",
    )
    .expect("write b/requirements.txt");

    let (sbom, _stderr) = scan_cdx(tmp.path());

    let Some(reason) = graph_completeness_reason(&sbom) else {
        // No reason emitted — soft-skip per U1 fallback. The unit-test
        // in `reason_codes.rs` already exercises `join_reason_codes`
        // with the m177 code + an existing code.
        eprintln!(
            "t008 soft-skip: no reason emitted on 2-workspace pip fixture — \
             m177 wire-format composition contract verified by unit test \
             `transitive_edges_unresolvable_composes_with_orphaned` in reason_codes.rs"
        );
        return;
    };

    // The m177 code MUST fire on this fixture (design-tier pypi
    // components exist).
    assert!(
        reason.contains(CODE_SUBSTRING),
        "SC-004: m177 code MUST fire on multi-workspace pip fixture; got {reason:?}"
    );

    // Look for a semicolon-join — indicates ≥2 codes fired.
    if reason.contains("; ") {
        // Great — genuine composition. Verify ≥1 other reason code
        // substring appears alongside m177's.
        let other_codes = [
            "orphaned-components-detected:",
            "multi-ecosystem-partial-root:",
            "root-selection-ambiguous:",
            "root-selection-failed:",
        ];
        let has_other = other_codes.iter().any(|c| reason.contains(c));
        assert!(
            has_other,
            "SC-004: semicolon-joined reason should contain ≥1 non-m177 code; got {reason:?}"
        );
    } else {
        // Only m177 fired — no genuine composition to assert here.
        // Wire-format composition is unit-tested elsewhere.
        eprintln!(
            "t008 soft-skip: only m177 code fired (no natural composition on this fixture) — \
             m177 wire-format composition contract verified by unit test in reason_codes.rs"
        );
    }
}
