shunit2_test(
    name="deploy-test",
    source="waybill-fixture-deploy-test.sh",
)

shunit2_tests(
    name="unit",
    sources=["*_test.sh"],
)

shell_source(
    name="fixture-setup",
    source="waybill-fixture-setup.sh",
)
