// build.rs combines:
//   - eBPF bytecode-build coordination (existing)
//   - Milestone 090 — fixture-repo fetch (existing)
//   - Milestone 108 — fingerprint-corpus SHA pin (new)
//
// The eBPF side is mostly a no-op: bytecode is compiled via
// `cargo xtask ebpf` and included via include_bytes_aligned! in
// loader.rs.
//
// The fixture-fetch side reads the pinned `waybill-test-fixtures`
// Git SHA from `<workspace>/tests/fixtures.rev`, ensures the fixture
// repo is cloned at that SHA into a per-host cache, and exposes the
// cache path to test code via the `WAYBILL_FIXTURES_DIR` compile-time
// env var. Cache-warm builds skip the network entirely. See
// specs/090-split-test-fixtures-repo/contracts/fixture-path-helper.md.
//
// The fingerprint-corpus SHA pin reads `<workspace>/tests/fingerprints.rev`
// and emits it as the `WAYBILL_FINGERPRINTS_CORPUS_SHA` compile-time
// env var consumed by the runtime corpus loader. Unlike fetch_fixtures,
// this build step does NOT touch the network — the runtime loader
// handles cache-miss fetch when `--fingerprints-corpus` is set at
// scan time. See specs/108-fingerprint-corpus/contracts/cache-layout.md.

use std::path::PathBuf;
use std::process::Command;

const FIXTURE_REPO_URL: &str = "https://github.com/kusari-sandbox/waybill-test-fixtures.git";

fn main() {
    println!("cargo:rerun-if-changed=build.rs");

    fetch_fixtures();
    emit_fingerprints_corpus_sha();
    emit_waybill_version_override();
}

/// Feature 229 (release-flow implementation) US3 — `WAYBILL_VERSION`
/// build-time env override — validation pass.
///
/// This build.rs step VALIDATES that any WAYBILL_VERSION set at the
/// shell env level is a well-formed SemVer string; panics if not (per
/// FR-004 fail-closed contract). It does NOT emit the override via
/// `cargo:rustc-env=` — that path was tried and rejected because
/// `cargo:rustc-env=` scopes emissions to the emitting crate only,
/// which broke propagation to `waybill-common` where the VERSION
/// const lives.
///
/// The actual override consumption happens at compile time inside
/// `waybill-common::VERSION` via `option_env!("WAYBILL_VERSION")` —
/// which reads the shell env directly. Cargo's built-in
/// `option_env!()` fingerprinting handles rebuild-on-env-change for
/// waybill-common; we only need `cargo:rerun-if-env-changed` here so
/// build.rs itself re-runs (to re-validate) on WAYBILL_VERSION change.
///
/// Validation:
///   - empty / whitespace-only → panic (fail-closed per FR-004)
///   - not-valid-SemVer → panic (fail-closed)
///   - valid SemVer → allow build to proceed
///
/// SemVer check is inline (no `semver` dep added) — the format we
/// accept is `X.Y.Z` OR `X.Y.Z-<pre-release>` OR `X.Y.Z+<build>` OR
/// `X.Y.Z-<pre>+<build>`, where X/Y/Z are non-negative integers and
/// pre-release / build segments are dot-separated ASCII alphanumerics.
///
/// Reference: contracts/build-rs-version-override.md; T015 verification.
fn emit_waybill_version_override() {
    println!("cargo:rerun-if-env-changed=WAYBILL_VERSION");
    let Ok(raw) = std::env::var("WAYBILL_VERSION") else {
        // Unset — write OUT_DIR file with CARGO_PKG_VERSION fallback.
        write_version_file(None);
        return;
    };
    let trimmed = raw.trim();
    if trimmed.is_empty() {
        panic!(
            "\nWAYBILL_VERSION is set but empty/whitespace — refuse to build.\n\
             Either unset it entirely OR provide a valid SemVer string\n\
             (e.g., `0.2.0-nightly.20260806`).\n"
        );
    }
    if !is_valid_semver(trimmed) {
        panic!(
            "\nWAYBILL_VERSION={trimmed:?} is not a valid SemVer.\n\
             Expected shape: `X.Y.Z` OR `X.Y.Z-<pre>` OR `X.Y.Z+<build>`\n\
             (e.g., `0.2.0`, `0.2.0-nightly.20260806`, `0.2.0-rc.1`).\n\
             See build.rs::is_valid_semver for the exact accepted grammar.\n"
        );
    }
    // Validation passed. Now write the effective value to OUT_DIR for
    // inclusion by `src/version.rs`. This is the correct cache-invalidation
    // path — `rerun-if-env-changed` re-runs build.rs on env change → new
    // OUT_DIR file → source-file recompile picks up new value.
    write_version_file(Some(trimmed));
}

/// Called from `main()` unconditionally so an OUT_DIR file exists even
/// when WAYBILL_VERSION is unset. When called from within
/// `emit_waybill_version_override` with a `Some(v)`, uses the override;
/// otherwise falls back to CARGO_PKG_VERSION.
fn write_version_file(override_value: Option<&str>) {
    let out_dir = std::env::var("OUT_DIR").expect("OUT_DIR must be set by cargo");
    let dest = std::path::PathBuf::from(&out_dir).join("waybill_version.rs");
    let value = override_value
        .map(String::from)
        .unwrap_or_else(|| std::env::var("CARGO_PKG_VERSION").expect("CARGO_PKG_VERSION"));
    let content = format!(
        "// Auto-generated by waybill-cli/build.rs (feature 229 US3).\n\
         // Do not edit — regenerated on every build; contents reflect the\n\
         // effective WAYBILL_VERSION override (shell env) or CARGO_PKG_VERSION fallback.\n\
         pub const VERSION: &str = \"{value}\";\n"
    );
    std::fs::write(&dest, content).unwrap_or_else(|e| {
        panic!("failed to write $OUT_DIR/waybill_version.rs at {}: {}", dest.display(), e)
    });
}

/// Minimal SemVer validator matching the subset waybill actually emits.
/// Accepts `X.Y.Z` core with optional `-<pre>` and/or `+<build>` segments.
/// Each of X/Y/Z is a non-negative integer with no leading zeros (except
/// zero itself). Pre-release + build segments are dot-separated
/// `[0-9A-Za-z-]+` identifiers.
fn is_valid_semver(s: &str) -> bool {
    // Split off the optional +build segment first.
    let (main_and_pre, build) = match s.find('+') {
        Some(i) => (&s[..i], Some(&s[i + 1..])),
        None => (s, None),
    };
    // Then split the pre-release from the version core.
    let (core, pre) = match main_and_pre.find('-') {
        Some(i) => (&main_and_pre[..i], Some(&main_and_pre[i + 1..])),
        None => (main_and_pre, None),
    };
    // Core: exactly three dot-separated non-negative integers.
    let core_parts: Vec<&str> = core.split('.').collect();
    if core_parts.len() != 3 {
        return false;
    }
    for part in &core_parts {
        if !is_valid_semver_numeric(part) {
            return false;
        }
    }
    // Pre + build (optional) — dot-separated identifiers of [0-9A-Za-z-].
    if let Some(pre) = pre {
        if !is_valid_semver_identifier_list(pre) {
            return false;
        }
    }
    if let Some(build) = build {
        if !is_valid_semver_identifier_list(build) {
            return false;
        }
    }
    true
}

fn is_valid_semver_numeric(s: &str) -> bool {
    if s.is_empty() {
        return false;
    }
    // No leading zeros unless the number IS zero.
    if s.len() > 1 && s.starts_with('0') {
        return false;
    }
    s.chars().all(|c| c.is_ascii_digit())
}

fn is_valid_semver_identifier_list(s: &str) -> bool {
    if s.is_empty() {
        return false;
    }
    s.split('.').all(|id| {
        !id.is_empty() && id.chars().all(|c| c.is_ascii_alphanumeric() || c == '-')
    })
}

fn fetch_fixtures() {
    let manifest_dir = PathBuf::from(
        std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR must be set by cargo"),
    );
    let workspace_root = manifest_dir
        .parent()
        .expect("CARGO_MANIFEST_DIR must have a parent (the workspace root)")
        .to_path_buf();
    let pin_path = workspace_root.join("tests").join("fixtures.rev");

    println!("cargo:rerun-if-changed={}", pin_path.display());
    println!("cargo:rerun-if-env-changed=WAYBILL_FIXTURE_CACHE");

    let sha_raw = std::fs::read_to_string(&pin_path).unwrap_or_else(|e| {
        panic!(
            "\nfailed to read fixture-repo pin at {}: {}\n\nThis commit predates the milestone-090 fixture split, OR the pin\nfile is missing. Either:\n  1. Check out a post-090 waybill revision that has tests/fixtures.rev, OR\n  2. Manually create the file with a 40-char hex SHA from\n     {url}\n",
            pin_path.display(),
            e,
            url = FIXTURE_REPO_URL,
        )
    });
    let sha = sha_raw.trim().to_string();
    let valid = sha.len() == 40
        && sha
            .chars()
            .all(|c| c.is_ascii_digit() || ('a'..='f').contains(&c));
    if !valid {
        panic!("\ntests/fixtures.rev MUST be a 40-char lowercase hex SHA; got {sha:?}\n");
    }

    let cache_parent = resolve_cache_parent();
    let cache_target = cache_parent.join(&sha);

    if cache_target.exists()
        && std::fs::read_dir(&cache_target)
            .map(|d| d.count())
            .unwrap_or(0)
            > 0
    {
        // Cache hit — skip fetch.
        println!(
            "cargo:rustc-env=WAYBILL_FIXTURES_DIR={}",
            cache_target.display()
        );
        return;
    }

    // Cache miss — clone + pin to exact SHA. `resolve_cache_parent`
    // already guarantees the parent directory exists.

    println!("cargo:warning=fetching waybill-test-fixtures @ {sha} (one-time per pin)");

    let cache_target_str = cache_target
        .to_str()
        .expect("cache target path must be UTF-8");

    let clone_status = Command::new("git")
        .args(["clone", FIXTURE_REPO_URL, cache_target_str])
        .status();
    if !matches!(clone_status, Ok(s) if s.success()) {
        let _ = std::fs::remove_dir_all(&cache_target);
        panic!(
            "\nFailed to fetch waybill-test-fixtures revision {sha}:\n    URL:   {url}\n    Cache: {cache}\n    Cause: git clone failed (status {clone_status:?})\n\nWorkaround:\n    1. Verify network access to github.com.\n    2. Manually clone:\n         git clone {url} {cache}\n         git -C {cache} reset --hard {sha}\n    3. Re-run cargo build.\n",
            url = FIXTURE_REPO_URL,
            cache = cache_target.display(),
        );
    }

    // Pin to exact SHA — clone defaults to default-branch HEAD; we
    // want the specific SHA from tests/fixtures.rev for reproducibility
    // across waybill commits.
    let reset_status = Command::new("git")
        .args(["-C", cache_target_str, "reset", "--hard", &sha])
        .status();
    if !matches!(reset_status, Ok(s) if s.success()) {
        let _ = std::fs::remove_dir_all(&cache_target);
        panic!(
            "\nFailed to pin {cache} to revision {sha}:\n    Cause: git reset --hard failed (status {reset_status:?})\n\nThis usually means the SHA isn't reachable from the default branch.\nFix: verify the SHA exists in {url} and is on the\ndefault branch's history.\n",
            cache = cache_target.display(),
            url = FIXTURE_REPO_URL,
        );
    }

    println!(
        "cargo:rustc-env=WAYBILL_FIXTURES_DIR={}",
        cache_target.display()
    );
}

/// Resolve a writable directory to host the fixture-repo cache.
///
/// Resolution order:
/// 1. `WAYBILL_FIXTURE_CACHE` env var (explicit operator override).
/// 2. `$HOME/.cache/waybill/fixtures/` on Unix /
///    `$USERPROFILE/.cache/waybill/fixtures/` on Windows.
/// 3. `$OUT_DIR/waybill-fixtures/` as a defensive fallback when (2)
///    isn't writable — cargo always sets `OUT_DIR` and guarantees it
///    is writable. Triggered in `cross` Docker containers where
///    `HOME=""` produces an unusable path like `/.cache/waybill/...`
///    that the container's root filesystem rejects.
///
/// Returns a path whose parent directory already exists and is
/// writable, so callers can `clone`/`reset` into a subdirectory of it
/// without panicking on permission errors.
fn resolve_cache_parent() -> PathBuf {
    let preferred = std::env::var("WAYBILL_FIXTURE_CACHE")
        .ok()
        .filter(|s| !s.is_empty())
        .map(PathBuf::from)
        .or_else(|| {
            let home = std::env::var("HOME")
                .ok()
                .or_else(|| std::env::var("USERPROFILE").ok())
                .filter(|s| !s.is_empty())?;
            Some(
                PathBuf::from(home)
                    .join(".cache")
                    .join("waybill")
                    .join("fixtures"),
            )
        });

    if let Some(path) = preferred {
        if std::fs::create_dir_all(&path).is_ok() {
            return path;
        }
        println!(
            "cargo:warning=fixture cache parent {} not writable; falling back to $OUT_DIR/waybill-fixtures/",
            path.display()
        );
    }

    // Fallback: $OUT_DIR is always set by cargo and is writable.
    let out_dir = std::env::var("OUT_DIR")
        .expect("cargo must set OUT_DIR in build.rs");
    let fallback = PathBuf::from(out_dir).join("waybill-fixtures");
    std::fs::create_dir_all(&fallback)
        .expect("OUT_DIR-based fixture cache fallback must be writable");
    fallback
}

/// Milestone 108 — read the pinned `kusari-sandbox/waybill-fingerprints`
/// SHA from `<workspace>/tests/fingerprints.rev` and emit it as the
/// `WAYBILL_FINGERPRINTS_CORPUS_SHA` compile-time env var.
///
/// Unlike `fetch_fixtures`, this step does NOT touch the network. The
/// runtime corpus loader handles cache-miss fetch when an operator
/// passes `--fingerprints-corpus` at scan time. The build only emits
/// the pin so `env!("WAYBILL_FINGERPRINTS_CORPUS_SHA")` resolves to
/// a known value in production code.
///
/// Validation: the file must contain a single 40-char lowercase hex
/// SHA (with optional trailing newline). Anything else panics the
/// build — the pin is reproducibility-critical and a malformed pin
/// would silently produce broken binaries.
fn emit_fingerprints_corpus_sha() {
    let manifest_dir = PathBuf::from(
        std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR must be set by cargo"),
    );
    let workspace_root = manifest_dir
        .parent()
        .expect("CARGO_MANIFEST_DIR must have a parent (the workspace root)")
        .to_path_buf();
    let pin_path = workspace_root.join("tests").join("fingerprints.rev");

    println!("cargo:rerun-if-changed={}", pin_path.display());

    let sha_raw = std::fs::read_to_string(&pin_path).unwrap_or_else(|e| {
        panic!(
            "\nfailed to read fingerprint-corpus pin at {}: {}\n\nThis commit predates the milestone-108 fingerprint-corpus split,\nOR the pin file is missing. Either:\n  1. Check out a post-108 waybill revision that has tests/fingerprints.rev, OR\n  2. Manually create the file with a 40-char hex SHA from\n     https://github.com/kusari-sandbox/waybill-fingerprints/commits/main\n",
            pin_path.display(),
            e,
        )
    });
    let sha = sha_raw.trim().to_string();
    let valid = sha.len() == 40
        && sha
            .chars()
            .all(|c| c.is_ascii_digit() || ('a'..='f').contains(&c));
    if !valid {
        panic!("\ntests/fingerprints.rev MUST be a 40-char lowercase hex SHA; got {sha:?}\n");
    }

    println!("cargo:rustc-env=WAYBILL_FINGERPRINTS_CORPUS_SHA={sha}");
}
