use serde::{Deserialize, Serialize};

use crate::types::timestamp::Timestamp;

/// Metadata about the trace session and its environment.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct TraceMetadata {
    pub tool: ToolInfo,
    pub trace_start: Timestamp,
    pub trace_end: Timestamp,
    pub target_process: ProcessInfo,
    pub host: HostInfo,
    pub generation_context: GenerationContext,
}

/// Identification of the tracing tool that produced the attestation.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct ToolInfo {
    pub name: String,
    pub version: String,
}

/// Information about the process being traced.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct ProcessInfo {
    pub pid: u32,
    pub command: String,
    pub cgroup_id: u64,
}

/// Information about the host where the trace was collected.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct HostInfo {
    pub os: String,
    pub kernel_version: String,
    pub arch: String,
    /// Distribution codename sampled from `/etc/os-release`
    /// (`VERSION_CODENAME`), e.g. `bookworm`, `trixie`, `jammy`. Used as the
    /// `distro` qualifier when emitting deb PURLs. Absent on non-Debian-family
    /// systems or when `/etc/os-release` is unavailable.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub distro_codename: Option<String>,
}

/// The context in which the attestation was generated. Propagates into
/// the CycloneDX `waybill:generation-context` property so downstream
/// consumers can tell apart authoritative build-time observations from
/// lower-confidence post-hoc scans.
#[derive(Clone, Debug, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum GenerationContext {
    /// Attestation generated from a build-time eBPF trace. Highest
    /// fidelity — every component is backed by a captured network or
    /// file event with evidence.
    #[serde(rename = "build-time-trace")]
    BuildTimeTrace,
    /// SBOM generated by walking a filesystem directory and matching
    /// known package-artifact path patterns. No eBPF; no attestation
    /// of the originating build. Confidence 0.70 per component.
    #[serde(rename = "filesystem-scan")]
    FilesystemScan,
    /// SBOM generated by extracting a container image's layers and
    /// scanning the resulting rootfs. Same machinery as filesystem
    /// scan, different subject.
    #[serde(rename = "container-image-scan")]
    ContainerImageScan,
}

impl GenerationContext {
    /// CISA 2026 § SBOM Generation Context vocabulary alias
    /// (`before-build` / `build` / `after-build`). Emitted alongside
    /// the waybill-native variant so consumers who key on CISA
    /// vocabulary can look the value up directly.
    ///
    /// Mapping (per spec `research.md` §R5):
    /// - `BuildTimeTrace` → `build` (observes syscalls during compile)
    /// - `FilesystemScan` → `after-build` (post-build artifacts)
    /// - `ContainerImageScan` → `after-build` (post-build image)
    ///
    /// waybill does not yet ship a `before-build` variant; source-
    /// only mode without build execution is reserved future work.
    pub fn as_cisa_2026_lifecycle(&self) -> &'static str {
        match self {
            Self::BuildTimeTrace => "build",
            Self::FilesystemScan => "after-build",
            Self::ContainerImageScan => "after-build",
        }
    }

    /// Wire-format waybill-native identifier — matches the serde
    /// rename (kebab-case). Available as an owned `&'static str` for
    /// annotation-string composition without triggering serde.
    pub fn as_waybill_native(&self) -> &'static str {
        match self {
            Self::BuildTimeTrace => "build-time-trace",
            Self::FilesystemScan => "filesystem-scan",
            Self::ContainerImageScan => "container-image-scan",
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn generation_context_serializes_as_kebab() {
        let json =
            serde_json::to_string(&GenerationContext::BuildTimeTrace).expect("serialize context");
        assert_eq!(json, "\"build-time-trace\"");

        let back: GenerationContext =
            serde_json::from_str("\"build-time-trace\"").expect("deserialize context");
        assert_eq!(back, GenerationContext::BuildTimeTrace);
    }

    #[test]
    fn trace_metadata_serde_round_trip() {
        let meta = TraceMetadata {
            tool: ToolInfo {
                name: "waybill".to_string(),
                version: "0.1.0".to_string(),
            },
            trace_start: Timestamp::now(),
            trace_end: Timestamp::now(),
            target_process: ProcessInfo {
                pid: 42,
                command: "cargo build".to_string(),
                cgroup_id: 12345,
            },
            host: HostInfo {
                os: "linux".to_string(),
                kernel_version: "6.5.0".to_string(),
                arch: "x86_64".to_string(),
                distro_codename: Some("bookworm".to_string()),
            },
            generation_context: GenerationContext::BuildTimeTrace,
        };

        let json = serde_json::to_string(&meta).expect("serialize metadata");
        let back: TraceMetadata = serde_json::from_str(&json).expect("deserialize metadata");
        assert_eq!(meta.tool.name, back.tool.name);
        assert_eq!(meta.host.arch, back.host.arch);
        assert_eq!(back.generation_context, GenerationContext::BuildTimeTrace);
    }

    #[test]
    fn cisa_2026_lifecycle_alias_maps_all_three_variants() {
        assert_eq!(
            GenerationContext::BuildTimeTrace.as_cisa_2026_lifecycle(),
            "build"
        );
        assert_eq!(
            GenerationContext::FilesystemScan.as_cisa_2026_lifecycle(),
            "after-build"
        );
        assert_eq!(
            GenerationContext::ContainerImageScan.as_cisa_2026_lifecycle(),
            "after-build"
        );
    }

    #[test]
    fn waybill_native_string_matches_serde_kebab() {
        assert_eq!(
            GenerationContext::BuildTimeTrace.as_waybill_native(),
            "build-time-trace"
        );
        assert_eq!(
            GenerationContext::FilesystemScan.as_waybill_native(),
            "filesystem-scan"
        );
        assert_eq!(
            GenerationContext::ContainerImageScan.as_waybill_native(),
            "container-image-scan"
        );
    }
}
