//! Parser for Yarn's `yarn.lock` file (milestone 106 US5, closes #274).
//!
//! Yarn has two distinct lockfile formats:
//!
//! 1. **v1 (Yarn Classic)** — text-based, indent-2 + indent-4 structure.
//!    Header: `# yarn lockfile v1`. Top-level entries are `"<descriptor>":`
//!    lines with descriptor strings like `"foo@^1.0.0"` (or comma-joined
//!    aliases like `"foo@^1.0.0", "foo@^1.1.0":`). Each entry's body
//!    declares `version "..."`, optional `resolved "..."`, optional
//!    `integrity ...`, and an optional `dependencies:` sub-block.
//!
//! 2. **Berry (Yarn 2+)** — YAML-shaped (parses with `serde_yaml`).
//!    Header: `# This file is generated by running "yarn install"`. Has a
//!    `__metadata:` block at the top. Descriptors carry an `npm:`
//!    protocol prefix (`"foo@npm:^1.0.0"`). Per-entry block uses YAML
//!    mappings (`version:`, `resolution:`, `dependencies:`, ...).
//!
//! Format detection is content-sniffed (we look for `__metadata:` at a
//! line start; presence ⇒ Berry, absence ⇒ v1). Both formats emit
//! `pkg:npm/<name>@<version>` PURLs (scoped names URL-encode the `@`
//! per PURL spec).
//!
//! Dependency edges from each entry's `dependencies:` map populate
//! `PackageDbEntry.depends`. The scan orchestrator looks each name up
//! against the in-scan entry set and drops unresolved ones — same
//! pattern as npm `package-lock.json`.

use std::collections::BTreeMap;
use std::path::Path;

use super::super::PackageDbEntry;
use super::build_npm_purl;

pub(super) fn read_yarn_lock(rootfs: &Path, _include_dev: bool) -> Option<Vec<PackageDbEntry>> {
    let path = rootfs.join("yarn.lock");
    let text = std::fs::read_to_string(&path).ok()?;
    let source_path = path.to_string_lossy().into_owned();
    let out = parse_yarn_lock(&text, &source_path);
    if out.is_empty() {
        None
    } else {
        Some(out)
    }
}

/// Parse a yarn.lock document (auto-detects v1 vs Berry).
pub(super) fn parse_yarn_lock(text: &str, source_path: &str) -> Vec<PackageDbEntry> {
    if is_berry(text) {
        parse_berry(text, source_path)
    } else {
        parse_v1(text, source_path)
    }
}

fn is_berry(text: &str) -> bool {
    text.lines()
        .take(50)
        .any(|line| line.trim_start().starts_with("__metadata:"))
}

// ────────────────────────────────────────────────────────────────────
// Berry parser (Yarn 2+)
// ────────────────────────────────────────────────────────────────────

fn parse_berry(text: &str, source_path: &str) -> Vec<PackageDbEntry> {
    // Skip the `__metadata:` block by stripping it from a deserialized
    // map. yarn.lock Berry is YAML-shaped — serde_yaml accepts it.
    let parsed: serde_yaml::Value = match serde_yaml::from_str(text) {
        Ok(v) => v,
        Err(e) => {
            tracing::warn!(
                path = %source_path,
                error = %e,
                "failed to parse Berry-format yarn.lock (skipping; FR-015)"
            );
            return Vec::new();
        }
    };
    let Some(mapping) = parsed.as_mapping() else {
        return Vec::new();
    };

    let mut out = Vec::new();
    for (raw_key, entry) in mapping {
        let Some(key_str) = raw_key.as_str() else {
            continue;
        };
        if key_str == "__metadata" {
            continue;
        }
        let Some(body) = entry.as_mapping() else {
            continue;
        };
        // Use the first descriptor in the (possibly comma-joined) key
        // to get the package name. Both `"foo@npm:^1.0.0"` and
        // `"foo@npm:^1.0.0, foo@npm:^2.0.0"` start with the name.
        let name = match descriptor_to_name(key_str) {
            Some(n) => n,
            None => continue,
        };
        let version = body
            .get(serde_yaml::Value::String("version".into()))
            .and_then(|v| v.as_str())
            .unwrap_or("")
            .trim()
            .to_string();
        if version.is_empty() {
            continue;
        }
        let dep_names = body
            .get(serde_yaml::Value::String("dependencies".into()))
            .and_then(|v| v.as_mapping())
            .map(|m| {
                m.keys()
                    .filter_map(|k| k.as_str().map(str::to_string))
                    .collect::<Vec<_>>()
            })
            .unwrap_or_default();
        if let Some(entry) = build_entry(&name, &version, source_path, dep_names) {
            out.push(entry);
        }
    }
    out
}

// ────────────────────────────────────────────────────────────────────
// v1 parser (Yarn Classic, line-oriented text format)
// ────────────────────────────────────────────────────────────────────
//
// Top-level entry shape:
//
//   "foo@^1.0.0", "foo@^1.1.0":
//     version "1.0.5"
//     resolved "https://..."
//     integrity sha512-...
//     dependencies:
//       bar "^2.0.0"

fn parse_v1(text: &str, source_path: &str) -> Vec<PackageDbEntry> {
    // Two-pass aggregator keyed by (name, version) so multi-alias
    // headers (where one block declares two aliases of the same coord)
    // don't double-emit.
    let mut acc: BTreeMap<(String, String), Vec<String>> = BTreeMap::new();

    let mut lines = text.lines().peekable();
    while let Some(line) = lines.next() {
        if !is_v1_entry_header(line) {
            continue;
        }
        let header_name = match v1_header_to_name(line) {
            Some(n) => n,
            None => continue,
        };
        // Collect the indented body for this entry until the next
        // unindented line (a comment or another header).
        let mut version: Option<String> = None;
        let mut in_deps_block = false;
        let mut dep_names: Vec<String> = Vec::new();
        while let Some(&body_line) = lines.peek() {
            let leading_ws = body_line.len() - body_line.trim_start().len();
            if !body_line.trim().is_empty() && leading_ws == 0 {
                break;
            }
            lines.next();
            let trimmed = body_line.trim();
            if trimmed.is_empty() {
                in_deps_block = false;
                continue;
            }
            if leading_ws == 2 {
                in_deps_block = false;
                if let Some(rest) = trimmed.strip_prefix("version ") {
                    version = Some(unquote(rest.trim()).to_string());
                } else if trimmed == "dependencies:" || trimmed == "optionalDependencies:" {
                    in_deps_block = true;
                }
            } else if leading_ws >= 4 && in_deps_block {
                // "name version-range" line; first token is the dep name.
                if let Some((dep_name, _rest)) = trimmed.split_once(char::is_whitespace) {
                    let dep_clean = unquote(dep_name.trim()).to_string();
                    if !dep_clean.is_empty() {
                        dep_names.push(dep_clean);
                    }
                }
            }
        }
        if let Some(v) = version {
            if !v.is_empty() {
                acc.entry((header_name.clone(), v))
                    .or_default()
                    .extend(dep_names);
            }
        }
    }

    let mut out = Vec::new();
    for ((name, version), deps) in acc {
        // De-duplicate dep names while preserving first-seen order.
        let mut seen: std::collections::BTreeSet<String> = Default::default();
        let unique: Vec<String> = deps
            .into_iter()
            .filter(|d| seen.insert(d.clone()))
            .collect();
        if let Some(entry) = build_entry(&name, &version, source_path, unique) {
            out.push(entry);
        }
    }
    out
}

fn is_v1_entry_header(line: &str) -> bool {
    // Top-level headers start at column 0, are non-comment, and end
    // with `:`. Examples:
    //   "foo@^1.0.0":
    //   foo@^1.0.0:
    //   "foo@^1.0.0", "foo@^1.1.0":
    if line.is_empty() {
        return false;
    }
    if line.starts_with(' ') || line.starts_with('\t') {
        return false;
    }
    if line.starts_with('#') {
        return false;
    }
    line.trim_end().ends_with(':')
}

fn v1_header_to_name(line: &str) -> Option<String> {
    let trimmed = line.trim_end_matches(':');
    // Split on `,` to get alias list; take the first descriptor.
    let first = trimmed.split(',').next()?.trim();
    descriptor_to_name(first)
}

/// Turn a descriptor like `foo@^1.0.0`, `"foo@^1.0.0"`, `"@types/node@^20.0.0"`,
/// or `"@types/node@npm:^20.0.0"` into the bare package name (`foo`,
/// `@types/node`, etc.).
fn descriptor_to_name(descriptor: &str) -> Option<String> {
    let unquoted = unquote(descriptor.trim());
    if unquoted.is_empty() {
        return None;
    }
    // Scoped names start with `@scope/name@...`. Strip the leading `@`
    // before searching for the descriptor's `@<version>` separator.
    let (search_target, scoped_prefix) = if let Some(rest) = unquoted.strip_prefix('@') {
        (rest, true)
    } else {
        (unquoted.as_ref(), false)
    };
    let at_idx = search_target.rfind('@')?;
    let name_part = &search_target[..at_idx];
    if name_part.is_empty() {
        return None;
    }
    Some(if scoped_prefix {
        format!("@{name_part}")
    } else {
        name_part.to_string()
    })
}

fn unquote(s: &str) -> String {
    let trimmed = s.trim();
    if trimmed.len() >= 2 && trimmed.starts_with('"') && trimmed.ends_with('"') {
        trimmed[1..trimmed.len() - 1].to_string()
    } else {
        trimmed.to_string()
    }
}

// ────────────────────────────────────────────────────────────────────
// Shared entry construction
// ────────────────────────────────────────────────────────────────────

fn build_entry(
    name: &str,
    version: &str,
    source_path: &str,
    depends: Vec<String>,
) -> Option<PackageDbEntry> {
    let purl = build_npm_purl(name, version)?;
    Some(PackageDbEntry {
        build_inclusion: None,
        purl,
        name: name.to_string(),
        version: version.to_string(),
        arch: None,
        source_path: source_path.to_string(),
        depends,
        maintainer: None,
        licenses: Vec::new(),
        lifecycle_scope: None,
        requirement_range: None,
        source_type: None,
        buildinfo_status: None,
        evidence_kind: None,
        binary_class: None,
        binary_stripped: None,
        linkage_kind: None,
        detected_go: None,
        confidence: None,
        binary_packed: None,
        raw_version: None,
        parent_purl: None,
        npm_role: None,
        co_owned_by: None,
        hashes: Vec::new(),
        sbom_tier: Some("source".to_string()),
        shade_relocation: None,
        extra_annotations: Default::default(),
        binary_role: None,
    })
}

#[cfg(test)]
#[cfg_attr(test, allow(clippy::unwrap_used))]
mod tests {
    use super::*;

    #[test]
    fn detects_berry_via_metadata_block() {
        let berry = "# Yarn install...\n\n__metadata:\n  version: 8\n";
        assert!(is_berry(berry));
        let v1 = "# yarn lockfile v1\n\n\"foo@^1.0.0\":\n  version \"1.0.0\"\n";
        assert!(!is_berry(v1));
    }

    #[test]
    fn v1_parses_basic_entries() {
        let text = r#"# yarn lockfile v1


"mikebom-fixture-lib@^1.0.0":
  version "1.2.3"
  resolved "https://example.invalid/mikebom-fixture-lib/-/mikebom-fixture-lib-1.2.3.tgz"
  integrity sha512-aaa

"mikebom-fixture-other@^2.0.0":
  version "2.3.4"
  resolved "https://example.invalid/mikebom-fixture-other/-/mikebom-fixture-other-2.3.4.tgz"
"#;
        let entries = parse_yarn_lock(text, "yarn.lock");
        assert_eq!(entries.len(), 2);
        let purls: Vec<&str> = entries.iter().map(|e| e.purl.as_str()).collect();
        assert!(purls.contains(&"pkg:npm/mikebom-fixture-lib@1.2.3"));
        assert!(purls.contains(&"pkg:npm/mikebom-fixture-other@2.3.4"));
    }

    #[test]
    fn v1_handles_scoped_names() {
        let text = r#"# yarn lockfile v1


"@mikebom-fixture/types-pkg@^4.0.0":
  version "4.5.6"
"#;
        let entries = parse_yarn_lock(text, "yarn.lock");
        assert_eq!(entries.len(), 1);
        assert_eq!(entries[0].name, "@mikebom-fixture/types-pkg");
        assert_eq!(entries[0].version, "4.5.6");
        assert_eq!(
            entries[0].purl.as_str(),
            "pkg:npm/%40mikebom-fixture/types-pkg@4.5.6"
        );
    }

    #[test]
    fn v1_handles_alias_lists() {
        // Two descriptors sharing one resolved version block.
        let text = r#"# yarn lockfile v1


"mikebom-fixture-alias@^1.0.0", "mikebom-fixture-alias@^1.1.0":
  version "1.5.0"
"#;
        let entries = parse_yarn_lock(text, "yarn.lock");
        assert_eq!(entries.len(), 1);
        assert_eq!(entries[0].name, "mikebom-fixture-alias");
        assert_eq!(entries[0].version, "1.5.0");
    }

    #[test]
    fn v1_extracts_dependency_edges() {
        let text = r#"# yarn lockfile v1


"mikebom-fixture-parent@^1.0.0":
  version "1.0.0"
  dependencies:
    "mikebom-fixture-child" "^2.0.0"
    mikebom-fixture-other "^3.0.0"

"mikebom-fixture-child@^2.0.0":
  version "2.0.0"
"#;
        let entries = parse_yarn_lock(text, "yarn.lock");
        let parent = entries
            .iter()
            .find(|e| e.name == "mikebom-fixture-parent")
            .unwrap();
        assert_eq!(parent.depends.len(), 2);
        assert!(parent
            .depends
            .contains(&"mikebom-fixture-child".to_string()));
        assert!(parent
            .depends
            .contains(&"mikebom-fixture-other".to_string()));
    }

    #[test]
    fn berry_parses_basic_entries() {
        let text = r#"# Yarn install...

__metadata:
  version: 8
  cacheKey: 10

"mikebom-fixture-lib@npm:^1.0.0":
  version: 1.2.3
  resolution: "mikebom-fixture-lib@npm:1.2.3"
  languageName: node
  linkType: hard

"@mikebom-fixture/types-pkg@npm:^4.0.0":
  version: 4.5.6
  resolution: "@mikebom-fixture/types-pkg@npm:4.5.6"
"#;
        let entries = parse_yarn_lock(text, "yarn.lock");
        assert_eq!(entries.len(), 2);
        let purls: Vec<&str> = entries.iter().map(|e| e.purl.as_str()).collect();
        assert!(purls.contains(&"pkg:npm/mikebom-fixture-lib@1.2.3"));
        assert!(purls.contains(&"pkg:npm/%40mikebom-fixture/types-pkg@4.5.6"));
    }

    #[test]
    fn berry_extracts_dependency_edges() {
        let text = r#"# Yarn install...

__metadata:
  version: 8

"mikebom-fixture-parent@npm:^1.0.0":
  version: 1.0.0
  resolution: "mikebom-fixture-parent@npm:1.0.0"
  dependencies:
    mikebom-fixture-child: ^2.0.0
    "@mikebom-fixture/scoped-dep": ^1.0.0

"mikebom-fixture-child@npm:^2.0.0":
  version: 2.0.0
  resolution: "mikebom-fixture-child@npm:2.0.0"
"#;
        let entries = parse_yarn_lock(text, "yarn.lock");
        let parent = entries
            .iter()
            .find(|e| e.name == "mikebom-fixture-parent")
            .unwrap();
        assert_eq!(parent.depends.len(), 2);
        assert!(parent
            .depends
            .contains(&"mikebom-fixture-child".to_string()));
        assert!(parent
            .depends
            .contains(&"@mikebom-fixture/scoped-dep".to_string()));
    }

    #[test]
    fn berry_skips_metadata_block() {
        let text = r#"__metadata:
  version: 8
"#;
        let entries = parse_yarn_lock(text, "yarn.lock");
        assert!(entries.is_empty());
    }

    #[test]
    fn malformed_returns_empty_no_panic() {
        let text = "this is { not a real } yarn lockfile";
        let entries = parse_yarn_lock(text, "yarn.lock");
        assert!(entries.is_empty());
    }
}
